# Generated by Django 4.2.7 on 2023-11-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_calendardate_symptom_info_disease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='related_diseases',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='disease',
            name='detail',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
