# Generated by Django 4.2.7 on 2023-12-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_disease_related_diseases_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('scheduleId', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=100)),
                ('temp', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100, null=True)),
                ('detail', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='info',
            name='calendar_date',
        ),
        migrations.DeleteModel(
            name='CalendarDate',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
