# Generated by Django 4.2.7 on 2023-12-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_schedule_remove_info_calendar_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='year',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='detail',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
